twitter:
    name: '@thetensreviews'
    consumer_key: Vlanf9jlu1Hw5UEXWK84dw'
    consumer_secret: 'EUCo6LTzsAvSrdn36H1NatPIiNtP73goR4s8KKY'
    access_token: '2230722482-V6c0rG1vILWGbBg91BxJSlnG4iIFrkf40yZiRwS'
    access_token_secret:'7HzgsShI5LTBC6tVLMYCauSwLSjff7sVV3C8KL1bwJsvf'